version: '3.8'

services:
  add_product:
    build:
      context: ./backend/add_product
    container_name: add_product_service
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb+srv://moranavraham11:AW9ta2zrTeZiWdSh@cluster0.dogxq.mongodb.net/shopping_cart?retryWrites=true&w=majority&appName=Cluster0
      - PYTHONIOENCODING=utf-8
    restart: always

  checkout:
    build:
      context: ./backend/checkout
    container_name: checkout_service
    ports:
      - "4002:4002"
    environment:
      - MONGO_URI=mongodb+srv://moranavraham11:AW9ta2zrTeZiWdSh@cluster0.dogxq.mongodb.net/shopping_cart?retryWrites=true&w=majority&appName=Cluster0
      - PYTHONIOENCODING=utf-8
    restart: always

  delete_product:
    build:
      context: ./backend/delete_product
    container_name: delete_product_service
    ports:
      - "4003:4003"
    environment:
      - MONGO_URI=mongodb+srv://moranavraham11:AW9ta2zrTeZiWdSh@cluster0.dogxq.mongodb.net/shopping_cart?retryWrites=true&w=majority&appName=Cluster0
      - PYTHONIOENCODING=utf-8
    restart: always

  get_cart:
    build:
      context: ./backend/get_cart
    container_name: get_cart_service
    ports:
      - "4005:4005"
    environment:
      - MONGO_URI=mongodb+srv://moranavraham11:AW9ta2zrTeZiWdSh@cluster0.dogxq.mongodb.net/shopping_cart?retryWrites=true&w=majority&appName=Cluster0
      - PYTHONIOENCODING=utf-8
    restart: always

  login:
    build:
      context: ./backend/login
    container_name: login_service
    ports:
      - "4006:4006"
    environment:
      - MONGO_URI=mongodb+srv://moranavraham11:AW9ta2zrTeZiWdSh@cluster0.dogxq.mongodb.net/shopping_cart?retryWrites=true&w=majority&appName=Cluster0
      - PYTHONIOENCODING=utf-8
    restart: always

  register:
    build:
      context: ./backend/register
    container_name: register_service
    ports:
      - "4007:4007"
    environment:
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=True
      - MAIL_USERNAME=tu_correo@gmail.com
      - MAIL_PASSWORD=tu_contraseña_de_gmail
      - MAIL_DEFAULT_SENDER=tu_correo@gmail.com
      - SECRET_KEY=your_secret_key
      - PYTHONIOENCODING=utf-8
    restart: always

  reset_cart:
    build:
      context: ./backend/reset_cart
    container_name: reset_cart_service
    ports:
      - "4008:4008"
    environment:
      - MONGO_URI=mongodb+srv://moranavraham11:AW9ta2zrTeZiWdSh@cluster0.dogxq.mongodb.net/shopping_cart?retryWrites=true&w=majority&appName=Cluster0
      - PYTHONIOENCODING=utf-8
    restart: always

  search_products:
    build:
      context: ./backend/search_products
    container_name: search_products_service
    ports:
      - "4009:4009"
    environment:
      - MONGO_URI=mongodb+srv://moranavraham11:AW9ta2zrTeZiWdSh@cluster0.dogxq.mongodb.net/shopping_cart?retryWrites=true&w=majority&appName=Cluster0
      - PYTHONIOENCODING=utf-8
    restart: always

  sort_cart:
    build:
      context: ./backend/sort_cart
    container_name: sort_cart_service
    ports:
      - "4010:4010"
    environment:
      - MONGO_URI=mongodb+srv://moranavraham11:AW9ta2zrTeZiWdSh@cluster0.dogxq.mongodb.net/shopping_cart?retryWrites=true&w=majority&appName=Cluster0
      - PYTHONIOENCODING=utf-8
    restart: always

  update_quantity:
    build:
      context: ./backend/update_quantity
    container_name: update_quantity_service
    ports:
      - "4011:4011"
    environment:
      - MONGO_URI=mongodb+srv://moranavraham11:AW9ta2zrTeZiWdSh@cluster0.dogxq.mongodb.net/shopping_cart?retryWrites=true&w=majority&appName=Cluster0
      - PYTHONIOENCODING=utf-8
    restart: always

  get_products:
    build:
      context: ./backend/get_products
    container_name: get_products_service
    ports:
      - "4012:4012"
    environment:
      - MONGO_URI=mongodb+srv://moranavraham11:AW9ta2zrTeZiWdSh@cluster0.dogxq.mongodb.net/shopping_cart?retryWrites=true&w=majority&appName=Cluster0
      - PYTHONIOENCODING=utf-8
    restart: always

  add_product_nodejs:
    build:
      context: ./nodejs-services/add_product
    container_name: add_product_nodejs_service
    ports:
      - "5007:5000"
    restart: always

  delete_product_nodejs:
    build:
      context: ./nodejs-services/delete_product
    container_name: delete_product_nodejs_service
    ports:
      - "5001:5001"
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    restart: always

  purchase_history:
    build:
      context: ./backend/purchase_history
    container_name: purchase_history_service
    ports:
      - "4014:4014"
    environment:
      - MONGO_URI=mongodb+srv://moranavraham11:AW9ta2zrTeZiWdSh@cluster0.dogxq.mongodb.net/shopping_cart?retryWrites=true&w=majority&appName=Cluster0
    restart: always

  inventory:
    build:
      context: ./backend/inventory
    container_name: inventory_service
    ports:
      - "4015:4015"
    environment:
      - MONGO_URI=mongodb+srv://moranavraham11:AW9ta2zrTeZiWdSh@cluster0.dogxq.mongodb.net/shopping_cart?retryWrites=true&w=majority&appName=Cluster0
    restart: always

  reviews:
    build:
      context: ./backend/reviews
    container_name: reviews_service
    ports:
      - "4016:4016"
    environment:
      - MONGO_URI=mongodb+srv://moranavraham11:AW9ta2zrTeZiWdSh@cluster0.dogxq.mongodb.net/shopping_cart?retryWrites=true&w=majority&appName=Cluster0
    restart: always