name: CI/CD Pipeline for Reset Cart Service

on:
  push:
    branches:
      - QA
#test
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend/reset_cart
        push: true
        tags: fernando615/reset_cart_service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST_RESET_CART }}
        username: ${{ secrets.EC2_USER_RESET_CART }}
        key: ${{ secrets.EC2_KEY_RESET_CART }}
        port: 22
        script: |
          docker stop reset_cart_service || true
          docker rm reset_cart_service || true
          docker pull fernando615/reset_cart_service:latest
          docker run -d -p 4006:4006 --name reset_cart_service fernando615/reset_cart_service:latest